image: docker:stable
services:
  - docker:18.09.7-dind
  
variables:
  DOCKER_DRIVER: overlay2
  SPRING_PROFILES_ACTIVE: aws-prod

stages:
  - build
  - package
  - deploy

maven-build:
  image: repo.etilizepak.com/maven-burraq
  stage: build
  script: "mvn package -B -DskipTests -Dspring.config.location=src/main/resources/bootstrap.yml spring-boot:repackage"
  artifacts:
    paths:
      - target/*.jar

  when: manual

docker-build:
  stage: package
  script:
  - docker build -t repo.etilizepak.com/$CI_PROJECT_NAME:latest -f src/main/docker/Dockerfile target/
  - docker push repo.etilizepak.com/$CI_PROJECT_NAME:latest

  when: manual

deploy-staging-K8S:
  stage: deploy
  image: repo.etilizepak.com/burraq-auth
  script:
    - cd /root/deployment
    - sed -i 's@project-name@'"$CI_PROJECT_NAME"'@g' kubernetes-staging.yml   
    - ./staging
  when: manual

  environment:
    name: staging-K8S
  
deploy-devops:
  stage: deploy
  image: repo.etilizepak.com/burraq-auth
  script:
    - cd /root/deployment
    - sed -i 's@project-name@'"$CI_PROJECT_NAME"'@g' kubernetes-devops.yml   
    - ./devops
  when: manual  

  environment:
    name: devops

k8s-deploy-production: 
  image: repo.etilizepak.com/burraq-auth
  stage: deploy
  script:
    - cd /root/deployment
    - sed -i 's@project-name@'"$CI_PROJECT_NAME"'@g' kubernetes-prod.yml 
    - ./production
  when: manual

  environment:
    name: aws-prod
    url: https://burraq.etilizepak.com
