spring:
  application:
    name: CategoryService
  profiles:
    active: dev
info:
  version: ${project.version}
endpoints:
  shutdown:
    enabled: true
server:
  port: 8080
mongeez:
  location: mongo-changelog/changelog-master.xml

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      database: category-service

---
spring:
  profiles: docker
  data:
    mongodb:
      host: categoryservicedb
      database: category-service
